Repository fairnesscoop/pictyschool, pull requests merged in 2021-01, with the labels that each got.

#33 Create school
  api/migrations/1609056073740-SchoolAddress.ts
  api/src/Application/School/Command/CreateSchoolCommand.ts
  api/src/Application/School/Command/CreateSchoolCommandHandler.spec.ts
  api/src/Application/School/Command/CreateSchoolCommandHandler.ts
  api/src/Application/User/Query/LoginQueryHandler.spec.ts
  api/src/Domain/School/Exception/SchoolAlreadyExistException.ts
  api/src/Domain/School/Repository/ISchoolRepository.ts
  api/src/Domain/School/School.entity.spec.ts
  api/src/Domain/School/School.entity.ts
  api/src/Domain/School/Specification/IsSchoolAlreadyExist.spec.ts
  api/src/Domain/School/Specification/IsSchoolAlreadyExist.ts
  api/src/Infrastructure/School/Action/CreateSchoolAction.ts
  api/src/Infrastructure/School/DTO/SchoolDTO.spec.ts
  api/src/Infrastructure/School/DTO/SchoolDTO.ts
  api/src/Infrastructure/School/Repository/SchoolRepository.ts
  api/src/Infrastructure/School/school.module.ts
  api/src/Infrastructure/User/DTO/LoginDTO.spec.ts
  api/src/Infrastructure/User/DTO/LoginDTO.ts
  api/src/Infrastructure/User/Decorator/LoggedPhotographer.ts
Labels: photographer

#34 List schools
  api/src/Application/Common/Pagination.ts
  api/src/Application/School/Query/GetSchoolsQuery.ts
  api/src/Application/School/Query/GetSchoolsQueryHandler.spec.ts
  api/src/Application/School/Query/GetSchoolsQueryHandler.ts
  api/src/Application/School/View/SchoolView.ts
  api/src/Domain/School/Repository/ISchoolRepository.ts
  api/src/Infrastructure/Common/DTO/IdDTO.spec.ts
  api/src/Infrastructure/Common/DTO/IdDTO.ts
  api/src/Infrastructure/Common/DTO/PaginationDTO.spec.ts
  api/src/Infrastructure/Common/DTO/PaginationDTO.ts
  api/src/Infrastructure/School/Action/GetSchoolsAction.ts
  api/src/Infrastructure/School/Repository/SchoolRepository.ts
  api/src/Infrastructure/School/school.module.ts
Labels: photographer

#35 Photographer profile
  api/src/Application/User/Command/UpdateProfileCommand.ts
  api/src/Application/User/Command/UpdateProfileCommandHandler.spec.ts
  api/src/Application/User/Command/UpdateProfileCommandHandler.ts
  api/src/Application/User/Query/GetPhotographerByIdQuery.ts
  api/src/Application/User/Query/GetPhotographerByIdQueryHandler.spec.ts
  api/src/Application/User/Query/GetPhotographerByIdQueryHandler.ts
  api/src/Application/User/Query/LoginQueryHandler.spec.ts
  api/src/Application/User/Query/LoginQueryHandler.ts
  api/src/Application/User/View/PhotographerView.ts
  api/src/Domain/User/Exception/EmailAlreadyExistException.ts
  api/src/Domain/User/Exception/PhotographerNotFoundException.ts
  api/src/Domain/User/Photographer.entity.spec.ts
  api/src/Domain/User/Photographer.entity.ts
  api/src/Domain/User/Repository/IPhotographerRepository.ts
  api/src/Domain/User/Specification/IsEmailAlreadyExist.spec.ts
  api/src/Domain/User/Specification/IsEmailAlreadyExist.ts
  api/src/Infrastructure/User/Action/GetMeAction.ts
  api/src/Infrastructure/User/Action/UpdateMeAction.ts
  api/src/Infrastructure/User/DTO/ProfileDTO.spec.ts
  api/src/Infrastructure/User/DTO/ProfileDTO.ts
  api/src/Infrastructure/User/Repository/PhotographerRepository.ts
  api/src/Infrastructure/User/user.module.ts
Labels: photographer

#36 Product model
  api/migrations/1609755423492-Product.ts
  api/src/Domain/Product/Product.entity.spec.ts
  api/src/Domain/Product/Product.entity.ts
  api/src/Domain/Product/Repository/IProductRepository.ts
  api/src/Infrastructure/Product/Repository/ProductRepository.ts
  api/src/Infrastructure/Product/product.module.ts
Labels: photographer

#37 Create product
  api/src/Application/Product/Command/CreateProductCommand.ts
  api/src/Application/Product/Command/CreateProductCommandHandler.spec.ts
  api/src/Application/Product/Command/CreateProductCommandHandler.ts
  api/src/Domain/Product/Exception/ProductAlreadyExistException.ts
  api/src/Domain/Product/Repository/IProductRepository.ts
  api/src/Domain/Product/Specification/IsProductAlreadyExist.spec.ts
  api/src/Domain/Product/Specification/IsProductAlreadyExist.ts
  api/src/Infrastructure/Product/Action/CreateProductAction.ts
  api/src/Infrastructure/Product/DTO/ProductDTO.spec.ts
  api/src/Infrastructure/Product/DTO/ProductDTO.ts
  api/src/Infrastructure/Product/Repository/ProductRepository.ts
  api/src/Infrastructure/Product/product.module.ts
  api/src/app.module.ts
Labels: photographer

#38 List products
  api/src/Application/Product/Query/GetProductsQuery.ts
  api/src/Application/Product/Query/GetProductsQueryHandler.spec.ts
  api/src/Application/Product/Query/GetProductsQueryHandler.ts
  api/src/Application/Product/View/ProductView.ts
  api/src/Application/School/View/SchoolView.ts
  api/src/Domain/Product/Repository/IProductRepository.ts
  api/src/Infrastructure/Product/Action/GetProductsAction.ts
  api/src/Infrastructure/Product/Repository/ProductRepository.ts
  api/src/Infrastructure/Product/product.module.ts
Labels: photographer

#39 Update product
  api/src/Application/Product/Command/UpdateProductCommand.ts
  api/src/Application/Product/Command/UpdateProductCommandHandler.spec.ts
  api/src/Application/Product/Command/UpdateProductCommandHandler.ts
  api/src/Domain/Product/Exception/ProductNotFoundException.ts
  api/src/Domain/Product/Product.entity.spec.ts
  api/src/Domain/Product/Product.entity.ts
  api/src/Domain/Product/Repository/IProductRepository.ts
  api/src/Infrastructure/Product/Action/UpdateProductAction.ts
  api/src/Infrastructure/Product/Repository/ProductRepository.ts
  api/src/Infrastructure/Product/product.module.ts
Labels: photographer

#41 List, add and edit products
  api/src/Application/Product/Query/GetProductByIdQuery.ts
  api/src/Application/Product/Query/GetProductByIdQueryHandler.spec.ts
  api/src/Application/Product/Query/GetProductByIdQueryHandler.ts
  api/src/Infrastructure/Product/Action/GetProductAction.ts
  api/src/Infrastructure/Product/product.module.ts
  client/i18n/fr.json
  client/src/components/Nav.svelte
  client/src/components/icons/FolderIcon.svelte
  client/src/normalizer/money.js
  client/src/routes/products/[id]/edit.svelte
  client/src/routes/products/_Form.svelte
  client/src/routes/products/_Table.svelte
  client/src/routes/products/add.svelte
  client/src/routes/products/index.svelte
Labels: client, photographer

#42 List and create schools
  client/i18n/fr.json
  client/src/components/Breadcrumb.svelte
  client/src/components/Nav.svelte
  client/src/components/Pagination.svelte
  client/src/components/ServerErrors.svelte
  client/src/components/header/Header.svelte
  client/src/components/header/Profile.svelte
  client/src/components/header/Search.svelte
  client/src/components/header/ThemeToggler.svelte
  client/src/components/icons/BurgerIcon.svelte
  client/src/components/icons/ChevronDownIcon.svelte
  client/src/components/icons/DarkThemeIcon.svelte
  client/src/components/icons/DashboardIcon.svelte
  client/src/components/icons/ErrorIcon.svelte
  client/src/components/icons/EyeIcon.svelte
  client/src/components/icons/FolderIcon.svelte
  client/src/components/icons/LightThemeIcon.svelte
  client/src/components/icons/LogoutIcon.svelte
  client/src/components/icons/PencilIcon.svelte
  client/src/components/icons/SchoolIcon.svelte
  client/src/components/icons/SearchIcon.svelte
  client/src/components/icons/TrashIcon.svelte
  client/src/components/icons/UserIcon.svelte
  client/src/components/inputs/Button.svelte
  client/src/components/inputs/Input.svelte
  client/src/components/links/AddLink.svelte
  client/src/components/links/EditLink.svelte
  client/src/components/links/Link.svelte
  client/src/components/links/SeeLink.svelte
  client/src/routes/_layout.svelte
  client/src/routes/login/index.svelte
  client/src/routes/profile/_Form.svelte
  client/src/routes/profile/index.svelte
  client/src/routes/schools/_Form.svelte
  client/src/routes/schools/_Table.svelte
  client/src/routes/schools/add.svelte
  client/src/routes/schools/index.svelte
Labels: client, photographer

#43 Edit school
  api/src/Application/Product/Command/UpdateProductCommandHandler.spec.ts
  api/src/Application/School/Command/UpdateSchoolCommand.ts
  api/src/Application/School/Command/UpdateSchoolCommandHandler.spec.ts
  api/src/Application/School/Command/UpdateSchoolCommandHandler.ts
  api/src/Application/School/Query/GetSchoolByIdQuery.ts
  api/src/Application/School/Query/GetSchoolByIdQueryHandler.spec.ts
  api/src/Application/School/Query/GetSchoolByIdQueryHandler.ts
  api/src/Domain/School/Exception/SchoolNotFoundException.ts
  api/src/Domain/School/Repository/ISchoolRepository.ts
  api/src/Domain/School/School.entity.spec.ts
  api/src/Domain/School/School.entity.ts
  api/src/Infrastructure/School/Action/GetSchoolAction.ts
  api/src/Infrastructure/School/Action/UpdateSchoolAction.ts
  api/src/Infrastructure/School/Repository/SchoolRepository.ts
  api/src/Infrastructure/School/school.module.ts
  client/i18n/fr.json
  client/src/components/Nav.svelte
  client/src/routes/schools/[id]/edit.svelte
  client/src/routes/schools/_Table.svelte
Labels: api, client, photographer

#44 School product model
  api/migrations/1610110860036-SchoolProduct.ts
  api/src/Domain/School/SchoolProduct.entity.spec.ts
  api/src/Domain/School/SchoolProduct.entity.ts
Labels: photographer

#46 Feat/school products view
  api/src/Application/School/Query/GetSchoolProductsQuery.ts
  api/src/Application/School/Query/GetSchoolProductsQueryHandler.spec.ts
  api/src/Application/School/Query/GetSchoolProductsQueryHandler.ts
  api/src/Domain/School/Repository/ISchoolProductRepository.ts
  api/src/Infrastructure/School/Action/GetSchoolProductsAction.ts
  api/src/Infrastructure/School/Repository/SchoolProductRepository.ts
  api/src/Infrastructure/School/school.module.ts
  client/src/components/links/SeeLink.svelte
  client/src/routes/schools/[id]/products/_Table.svelte
  client/src/routes/schools/[id]/products/index.svelte
  client/src/routes/schools/_Table.svelte
Labels: photographer

#48 api: remove school produt
  README.md
  api/src/Application/Product/Command/UpdateProductCommandHandler.spec.ts
  api/src/Application/Product/Command/UpdateProductCommandHandler.ts
  api/src/Application/School/Command/Product/RemoveSchoolProductCommand.ts
  api/src/Application/School/Command/Product/RemoveSchoolProductCommandHandler.spec.ts
  api/src/Application/School/Command/Product/RemoveSchoolProductCommandHandler.ts
  api/src/Application/School/Command/UpdateSchoolCommandHandler.spec.ts
  api/src/Application/School/Command/UpdateSchoolCommandHandler.ts
  api/src/Application/School/Query/GetSchoolProductsQueryHandler.ts
  api/src/Application/School/Query/Product/GetSchoolProductByIdQueryHandler.ts
  api/src/Domain/School/Repository/ISchoolProductRepository.ts
  api/src/Infrastructure/School/Action/Product/RemoveSchoolProductAction.ts
  api/src/Infrastructure/School/Repository/SchoolProductRepository.ts
  api/src/Infrastructure/School/school.module.ts
  api/src/main.ts
  client/i18n/fr.json
  client/src/routes/schools/[id]/products/_Table.svelte
Labels: photographer

#49 Count school products
  api/src/Application/School/Query/Product/CountSchoolProductsQuery.ts
  api/src/Application/School/Query/Product/CountSchoolProductsQueryHandler.spec.ts
  api/src/Application/School/Query/Product/CountSchoolProductsQueryHandler.ts
  api/src/Application/School/Query/Product/GetSchoolProductsQuery.ts
  api/src/Application/School/Query/Product/GetSchoolProductsQueryHandler.spec.ts
  api/src/Application/School/Query/Product/GetSchoolProductsQueryHandler.ts
  api/src/Domain/School/Repository/ISchoolProductRepository.ts
  api/src/Infrastructure/School/Action/Product/CountSchoolProductsAction.ts
  api/src/Infrastructure/School/Action/Product/GetSchoolProductsAction.ts
  api/src/Infrastructure/School/Repository/SchoolProductRepository.ts
  api/src/Infrastructure/School/school.module.ts
  client/src/routes/schools/[id]/_CardProduct.svelte
Labels: photographer
