Repository fairnesscoop/pictyschool, pull requests merged in 2021-04, with the labels that each got.

#68 School users managment
  api/migrations/1617268818418-SchoolUsers.ts
  api/src/Application/School/Command/AssignDirectorToSchoolCommandHandler.ts
  api/src/Application/School/Command/CreateSchoolCommand.ts
  api/src/Application/School/Command/CreateSchoolCommandHandler.spec.ts
  api/src/Application/School/Command/CreateSchoolCommandHandler.ts
  api/src/Application/School/Command/UpdateSchoolCommand.ts
  api/src/Application/School/Command/UpdateSchoolCommandHandler.spec.ts
  api/src/Application/School/Command/UpdateSchoolCommandHandler.ts
  api/src/Application/School/Command/User/AssignUserToSchoolCommand.ts
  api/src/Application/School/Command/User/AssignUserToSchoolCommandHandler.spec.ts
  api/src/Application/School/Command/User/AssignUserToSchoolCommandHandler.ts
  api/src/Application/School/Query/GetSchoolByIdQueryHandler.spec.ts
  api/src/Application/School/Query/GetSchoolByIdQueryHandler.ts
  api/src/Application/School/Query/GetSchoolsQueryHandler.spec.ts
  api/src/Application/School/Query/GetSchoolsQueryHandler.ts
  api/src/Application/School/Query/User/GetSchoolUsersQuery.ts
  api/src/Application/School/Query/User/GetSchoolUsersQueryHandler.spec.ts
  api/src/Application/School/Query/User/GetSchoolUsersQueryHandler.ts
  api/src/Application/School/View/SchoolDetailView.ts
  api/src/Application/School/View/UserSchoolView.ts
  api/src/Domain/Lead/Lead.entity.ts
  api/src/Domain/School/AbstractSchool.ts
  api/src/Domain/School/Repository/ISchoolRepository.ts
  api/src/Domain/School/Repository/ISchoolUserRepository.ts
  api/src/Domain/School/School.entity.spec.ts
  api/src/Domain/School/School.entity.ts
  api/src/Domain/School/SchoolProduct.entity.spec.ts
  api/src/Domain/School/SchoolUser.entity.spec.ts
  api/src/Domain/School/SchoolUser.entity.ts
  api/src/Domain/User/Exception/UserAlreadyAssignedToSchoolException.ts
  api/src/Domain/User/Exception/UserShouldBeDirectorException.ts
  api/src/Domain/User/Specification/CanUserAccessToSchool.spec.ts
  api/src/Domain/User/Specification/CanUserAccessToSchool.ts
  api/src/Domain/User/Specification/IsUserAlreadyAssignedToSchool.spec.ts
  api/src/Domain/User/Specification/IsUserAlreadyAssignedToSchool.ts
  api/src/Infrastructure/Lead/DTO/LeadDTO.spec.ts
  api/src/Infrastructure/Lead/DTO/LeadDTO.ts
  api/src/Infrastructure/School/Action/CreateSchoolAction.ts
  api/src/Infrastructure/School/Action/UpdateSchoolAction.ts
  api/src/Infrastructure/School/Action/User/AssignUserToSchoolAction.ts
  api/src/Infrastructure/School/Action/User/GetSchoolUsersAction.ts
  api/src/Infrastructure/School/DTO/AbstractSchoolDTO.ts
  api/src/Infrastructure/School/Repository/SchoolRepository.ts
  api/src/Infrastructure/School/Repository/SchoolUserRepository.ts
  api/src/Infrastructure/School/school.module.ts
  client/i18n/fr.json
  client/src/components/icons/DirectorIcon.svelte
  client/src/routes.js
  client/src/routes/admin/leads/_Table.svelte
  client/src/routes/admin/schools/[id]/_CardClass.svelte
  client/src/routes/admin/schools/[id]/_CardDirector.svelte
  client/src/routes/admin/schools/[id]/_InformationSheet.svelte
  client/src/routes/admin/schools/[id]/_SchoolUsers.svelte
  client/src/routes/admin/schools/[id]/director/_Detail.svelte
  client/src/routes/admin/schools/[id]/director/add.svelte
  client/src/routes/admin/schools/[id]/edit.svelte
  client/src/routes/admin/schools/[id]/index.svelte
  client/src/routes/admin/schools/[id]/users/index.svelte
  client/src/routes/admin/schools/_Form.svelte
  client/src/routes/admin/schools/_Table.svelte
Labels: tech

#69 Delete user
  api/src/Application/School/Query/User/GetSchoolUsersQueryHandler.spec.ts
  api/src/Application/School/Query/User/GetSchoolUsersQueryHandler.ts
  api/src/Application/School/View/UserSchoolView.ts
  api/src/Application/User/Command/RemoveUserCommand.ts
  api/src/Application/User/Command/RemoveUserCommandHandler.spec.ts
  api/src/Application/User/Command/RemoveUserCommandHandler.ts
  api/src/Domain/User/Exception/CantRemoveYourselfException.ts
  api/src/Domain/User/Repository/IUserRepository.ts
  api/src/Infrastructure/School/Action/User/GetSchoolUsersAction.ts
  api/src/Infrastructure/School/Repository/SchoolUserRepository.ts
  api/src/Infrastructure/User/Action/RemoveUserAction.ts
  api/src/Infrastructure/User/Repository/UserRepository.ts
  api/src/Infrastructure/User/user.module.ts
  client/i18n/fr.json
  client/src/routes/admin/schools/[id]/_SchoolUsers.svelte
Labels: photographer

#75 Remove event
  api/src/Application/Calendar/Command/RemoveEventCommand.ts
  api/src/Application/Calendar/Command/RemoveEventCommandHandler.spec.ts
  api/src/Application/Calendar/Command/RemoveEventCommandHandler.ts
  api/src/Domain/Calendar/Repository/IEventRepository.ts
  api/src/Infrastructure/Calendar/Action/RemoveEventAction.ts
  api/src/Infrastructure/Calendar/Repository/EventRepository.ts
  api/src/Infrastructure/Calendar/calendar.module.ts
  client/src/routes/admin/calendar/[id]/index.svelte
Labels: photographer

#78 Shooting model
  api/migrations/1618659343512-Shooting.ts
  api/src/Application/School/Command/CreateSchoolCommand.ts
  api/src/Application/School/Command/CreateSchoolCommandHandler.spec.ts
  api/src/Application/School/Command/CreateSchoolCommandHandler.ts
  api/src/Application/School/Command/UpdateSchoolCommand.ts
  api/src/Application/School/Command/UpdateSchoolCommandHandler.spec.ts
  api/src/Application/School/Command/UpdateSchoolCommandHandler.ts
  api/src/Application/School/Query/GetSchoolByIdQueryHandler.spec.ts
  api/src/Application/School/Query/GetSchoolByIdQueryHandler.ts
  api/src/Application/School/View/SchoolDetailView.ts
  api/src/Domain/Calendar/Event.entity.ts
  api/src/Domain/School/AccessToken.entity.spec.ts
  api/src/Domain/School/AccessToken.entity.ts
  api/src/Domain/School/Photo.entity.spec.ts
  api/src/Domain/School/Photo.entity.ts
  api/src/Domain/School/Repository/IAccessTokenRepository.ts
  api/src/Domain/School/Repository/IShootingRepository.ts
  api/src/Domain/School/School.entity.spec.ts
  api/src/Domain/School/School.entity.ts
  api/src/Domain/School/Shooting.entity.spec.ts
  api/src/Domain/School/Shooting.entity.ts
  api/src/Domain/School/Voucher.entity.ts
  api/src/Infrastructure/School/Action/CreateSchoolAction.ts
  api/src/Infrastructure/School/Action/UpdateSchoolAction.ts
  api/src/Infrastructure/School/DTO/SchoolDTO.spec.ts
  api/src/Infrastructure/School/DTO/SchoolDTO.ts
  api/src/Infrastructure/School/Repository/AccessTokenRepository.ts
  api/src/Infrastructure/School/Repository/SchoolRepository.ts
  api/src/Infrastructure/School/Repository/ShootingRepository.ts
  api/src/Infrastructure/School/school.module.ts
  client/i18n/fr.json
  client/src/routes/admin/schools/[id]/edit.svelte
  client/src/routes/admin/schools/_Form.svelte
Labels: tech

#77 avoid to overwrite config files if make install is run
  Makefile
Labels: ready to review

#80 List and count shootings
  api/migrations/1618659343512-Shooting.ts
  api/src/Application/School/Query/Product/GetSchoolProductsQueryHandler.spec.ts
  api/src/Application/School/Query/Shooting/CountShootingsBySchoolQuery.ts
  api/src/Application/School/Query/Shooting/CountShootingsBySchoolQueryHandler.spec.ts
  api/src/Application/School/Query/Shooting/CountShootingsBySchoolQueryHandler.ts
  api/src/Application/School/Query/Shooting/GetShootingsBySchoolQuery.ts
  api/src/Application/School/Query/Shooting/GetShootingsBySchoolQueryHandler.spec.ts
  api/src/Application/School/Query/Shooting/GetShootingsBySchoolQueryHandler.ts
  api/src/Application/School/View/ShootingView.ts
  api/src/Domain/School/Repository/IShootingRepository.ts
  api/src/Domain/School/Shooting.entity.spec.ts
  api/src/Domain/School/Shooting.entity.ts
  api/src/Infrastructure/School/Action/Shooting/CountSchoolShootingsAction.ts
  api/src/Infrastructure/School/Action/Shooting/GetSchoolShootingsAction.ts
  api/src/Infrastructure/School/Repository/ShootingRepository.ts
  api/src/Infrastructure/School/school.module.ts
  client/i18n/fr.json
  client/src/routes/admin/schools/[id]/_CardShooting.svelte
  client/src/routes/admin/schools/[id]/shootings/_Table.svelte
  client/src/routes/admin/schools/[id]/shootings/index.svelte
Labels: photographer

#81 Discount model
  api/migrations/1618750529200-Discount.ts
  api/src/Domain/School/Discount.entity.spec.ts
  api/src/Domain/School/Discount.entity.ts
  api/src/Domain/School/Repository/IDiscountRepository.ts
  api/src/Infrastructure/School/Repository/DiscountRepository.ts
  api/src/Infrastructure/School/school.module.ts
  client/i18n/fr.json
  client/src/routes/admin/schools/[id]/_CardDiscount.svelte
  client/src/routes/admin/schools/[id]/index.svelte
Labels: photographer

#82 List and create discounts
  api/migrations/1618768550317-DiscountType.ts
  api/src/Application/School/Command/Discount/CreateDiscountCommand.ts
  api/src/Application/School/Command/Discount/CreateDiscountCommandHandler.spec.ts
  api/src/Application/School/Command/Discount/CreateDiscountCommandHandler.ts
  api/src/Application/School/Query/Discount/CountDiscountsBySchoolQuery.ts
  api/src/Application/School/Query/Discount/CountDiscountsBySchoolQueryHandler.spec.ts
  api/src/Application/School/Query/Discount/CountDiscountsBySchoolQueryHandler.ts
  api/src/Application/School/Query/Discount/GetDiscountsBySchoolQuery.ts
  api/src/Application/School/Query/Discount/GetDiscountsBySchoolQueryHandler.spec.ts
  api/src/Application/School/Query/Discount/GetDiscountsBySchoolQueryHandler.ts
  api/src/Application/School/View/DiscountView.ts
  api/src/Domain/School/Discount.entity.spec.ts
  api/src/Domain/School/Discount.entity.ts
  api/src/Domain/School/Exception/DiscountAlreadyExistException.ts
  api/src/Domain/School/Repository/IDiscountRepository.ts
  api/src/Domain/School/Specification/Discount/IsDiscountAlreadyExist.spec.ts
  api/src/Domain/School/Specification/Discount/IsDiscountAlreadyExist.ts
  api/src/Infrastructure/School/Action/Discount/CountSchoolDiscountsAction.ts
  api/src/Infrastructure/School/Action/Discount/CreateDiscountAction.ts
  api/src/Infrastructure/School/Action/Discount/GetSchoolDiscountsAction.ts
  api/src/Infrastructure/School/DTO/DiscountDTO.spec.ts
  api/src/Infrastructure/School/DTO/DiscountDTO.ts
  api/src/Infrastructure/School/DTO/SchoolDTO.spec.ts
  api/src/Infrastructure/School/Repository/DiscountRepository.ts
  api/src/Infrastructure/School/school.module.ts
  client/i18n/fr.json
  client/src/routes/admin/schools/[id]/_CardDiscount.svelte
  client/src/routes/admin/schools/[id]/discounts/_Form.svelte
  client/src/routes/admin/schools/[id]/discounts/_Table.svelte
  client/src/routes/admin/schools/[id]/discounts/add.svelte
  client/src/routes/admin/schools/[id]/discounts/index.svelte
Labels: photographer

#83 Remove discount
  api/src/Application/School/Command/Discount/RemoveDiscountCommand.ts
  api/src/Application/School/Command/Discount/RemoveDiscountCommandHandler.spec.ts
  api/src/Application/School/Command/Discount/RemoveDiscountCommandHandler.ts
  api/src/Domain/School/Exception/DiscountNotFoundException.ts
  api/src/Domain/School/Repository/IDiscountRepository.ts
  api/src/Infrastructure/School/Action/Discount/RemoveDiscountAction.ts
  api/src/Infrastructure/School/Repository/DiscountRepository.ts
  api/src/Infrastructure/School/school.module.ts
  client/i18n/fr.json
  client/src/routes/admin/schools/[id]/discounts/_Table.svelte
  client/src/routes/admin/schools/[id]/discounts/index.svelte
Labels: photographer

#84 Remove product
  api/src/Application/Calendar/Command/RemoveEventCommandHandler.spec.ts
  api/src/Application/Lead/Command/RemoveLeadCommandHandler.spec.ts
  api/src/Application/Product/Command/RemoveProductCommand.ts
  api/src/Application/Product/Command/RemoveProductCommandHandler.spec.ts
  api/src/Application/Product/Command/RemoveProductCommandHandler.ts
  api/src/Application/School/Command/Discount/RemoveDiscountCommandHandler.spec.ts
  api/src/Application/School/Command/Product/RemoveSchoolProductCommandHandler.spec.ts
  api/src/Application/School/Command/User/RemoveSchoolUserCommandHandler.spec.ts
  api/src/Application/School/Command/Voucher/RemoveVoucherCommandHandler.spec.ts
  api/src/Application/User/Command/RemoveUserCommandHandler.spec.ts
  api/src/Domain/Product/Repository/IProductRepository.ts
  api/src/Infrastructure/Product/Action/RemoveProductAction.ts
  api/src/Infrastructure/Product/Repository/ProductRepository.ts
  api/src/Infrastructure/Product/product.module.ts
  client/i18n/fr.json
  client/src/routes/admin/leads/index.svelte
  client/src/routes/admin/products/_Table.svelte
  client/src/routes/admin/products/index.svelte
  client/src/routes/admin/schools/[id]/discounts/_Table.svelte
Labels: photographer

#86 Association of products in the school when it was created
  api/src/Application/Product/Query/GetProductByIdQueryHandler.spec.ts
  api/src/Application/Product/Query/GetProductByIdQueryHandler.ts
  api/src/Application/Product/Query/GetProductsQueryHandler.spec.ts
  api/src/Application/Product/Query/GetProductsQueryHandler.ts
  api/src/Application/School/Command/CreateSchoolCommandHandler.spec.ts
  api/src/Application/School/Command/CreateSchoolCommandHandler.ts
  api/src/Application/School/Event/SchoolCreatedEvent.ts
  api/src/Application/School/EventListener/SchoolCreatedEventListener.spec.ts
  api/src/Application/School/EventListener/SchoolCreatedEventListener.ts
  api/src/Application/School/Query/Product/GetSchoolProductByIdQueryHandler.spec.ts
  api/src/Application/School/Query/Product/GetSchoolProductByIdQueryHandler.ts
  api/src/Application/School/Query/Product/GetSchoolProductsQueryHandler.spec.ts
  api/src/Application/School/Query/Product/GetSchoolProductsQueryHandler.ts
  api/src/Domain/Product/Product.entity.spec.ts
  api/src/Domain/Product/Product.entity.ts
  api/src/Domain/Product/Repository/IProductRepository.ts
  api/src/Domain/School/SchoolProduct.entity.spec.ts
  api/src/Domain/School/SchoolProduct.entity.ts
  api/src/Infrastructure/Product/Repository/ProductRepository.ts
  api/src/Infrastructure/School/school.module.ts
Labels: photographer, ready to review

#87 Get shooting by id
  api/src/Application/School/Query/Shooting/GetSchootingByIdQuery.ts
  api/src/Application/School/Query/Shooting/GetShootingByIdQueryHandler.spec.ts
  api/src/Application/School/Query/Shooting/GetShootingByIdQueryHandler.ts
  api/src/Domain/School/Exception/ShootingNotFoundException.ts
  api/src/Domain/School/Repository/IShootingRepository.ts
  api/src/Infrastructure/School/Action/Shooting/GetShootingAction.ts
  api/src/Infrastructure/School/Repository/ShootingRepository.ts
  api/src/Infrastructure/School/school.module.ts
  client/i18n/fr.json
  client/src/routes/admin/schools/[id]/shootings/[shootingId]/index.svelte
  client/src/routes/admin/schools/[id]/shootings/_Table.svelte
Labels: photographer
